### ISSUE TITLE
Update to v1.40.0

### ISSUE THREAD

**Issue by af1** [thomascenni/umami#1]
Hi there, 

How would one update to the latest version? Or perhaps make the script always use the latest version?

I'm not super experienced using Render. I appreciate any help but totally understand if support is not something you offer.

Thank you for the super easy to use script!

**Comment by af1** [comment]
I figured it out with a bit of tinkering. Thanks again for the great script.

**Comment by thomascenni** [comment]
Hi @af1 
Just updated manually to the latest version. I don't want to use the latest tag, I always prefer knowing what version I am using.

**Comment by af1** [comment]
I figured as much, and it does make sense. Thanks again.
